name: AI Quality Audit

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run AI Audit
        run: npm run ai-audit

      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analysis
          path: analysis/
